export const GET_ROOMS_REQUEST = "GET_ROOMS_REQUEST";
export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const GET_ROOMS_FAILURE = "GET_ROOMS_FAILURE";
export const GET_FILTER_ROOM = "GET_FILTER_ROOM";

export const SET_ISOPEN = "SET_ISOPEN";